# These are supported funding model platforms

github: [skifli] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: exeme-project # Replace with a single Open Collective username
