name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug you experienced in a conscise manner.
      placeholder: Tell us what happened in a conscise manner.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Describe how to consistently reproduce the bug.
      placeholder: Tell us how to consistently reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Describe what you expected to happen.
      placeholder: Tell us what you expected to happened.
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: Describe what you actually happened.
      placeholder: Tell us what actually happened (screenshots are welcome).
    validations:
      required: true
  - type: textarea
    id: environment-info
    attributes:
      label: Environment Info
      description: What OS and Exeme Language version did the bug occur on?
      placeholder: Tell us the OS and Exeme Language version the bug occured on.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Is there any additional information that may be useful in solving the bug?
      placeholder: Tell us any additional information.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: The Code of Conduct can be found [here](github.com/exeme-project/exeme-lang/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
