# Part of the Exeme language project, under the MIT license. See '/LICENSE' for license information. SPDX-License-Identifier: MIT License.

blank_issues_enabled: false

contact_links:
  - name: I want to join the Discord
    url: https://discord.gg/9SCfXMZKSf
    about: Most activity around Exeme happens on our Discord.
