name: Feature Request
description: Request a feature
title: "[FEATURE]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you would like to be added to Exeme Language.
      placeholder: Tell us about your proposed feature.
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe use case(s) for your proposed feature.
      placeholder: Tell us about use case(s) for your proposed feature.
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Describe alternate solutions you have considered for the proposed feature.
      placeholder: Tell us about alternate solutions you have considered for the proposed feature.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Is there any additional information that may be useful?
      placeholder: Tell us any additional information.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: The Code of Conduct can be found [here](github.com/exeme-project/exeme-lang/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
